# Generated by Django 4.0.3 on 2022-04-26 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('globalScore', models.IntegerField()),
                ('timeFinish', models.IntegerField()),
                ('timePlayed', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default=0, max_length=20)),
                ('username', models.CharField(default=0, max_length=20)),
                ('email', models.CharField(default=0, max_length=30)),
                ('password', models.CharField(default=0, max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('country', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('attemps', models.IntegerField()),
                ('timeToSolve', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
