# Generated by Django 4.0.3 on 2022-04-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.AlterField(
            model_name='global',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='plays',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
