# Generated by Django 4.0.3 on 2022-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='timeFinish',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='global',
            name='timePlayed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plays',
            name='timeToSolve',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
