# Generated by Django 4.0.3 on 2022-04-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gamertag', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
