# Generated by Django 4.0.3 on 2022-04-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boomSite', '0002_player_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='gamertag',
            new_name='username',
        ),
    ]
